import type { NBFCApplicationListItem } from "@/lib/types";

/** Synthetic queue for NBFC demos when the database queue is empty. */
export const NBFC_DEMO_PIPELINE: NBFCApplicationListItem[] = [
  {
    id: "demo-aria-m",
    applicant_name: "Aria Mehta",
    institute: "IIT Bombay",
    program: "MS Computer Science",
    target_country: "United States",
    risk_label: "low",
    placement_prob_6m: 0.72,
    salary_band_low_lpa: 42,
    salary_band_high_lpa: 58,
    loan_amount_requested: 1_850_000,
    status: "under_review",
    submitted_at: new Date().toISOString(),
    document_completeness_pct: 83,
    roi_payback_years: 2.4,
    scholarship_dependency: "high",
    candidate_quality: "strong",
    repayment_confidence_pct: 86,
  },
  {
    id: "demo-james-k",
    applicant_name: "James K.",
    institute: "University of Toronto",
    program: "MEng Software",
    target_country: "Canada",
    risk_label: "medium",
    placement_prob_6m: 0.58,
    salary_band_low_lpa: 28,
    salary_band_high_lpa: 38,
    loan_amount_requested: 1_200_000,
    status: "submitted",
    submitted_at: new Date().toISOString(),
    document_completeness_pct: 66,
    roi_payback_years: 3.1,
    scholarship_dependency: "medium",
    candidate_quality: "watch",
    repayment_confidence_pct: 71,
  },
  {
    id: "demo-sofia-l",
    applicant_name: "Sofia Laurent",
    institute: "Sciences Po",
    program: "MPP / Data",
    target_country: "United Kingdom",
    risk_label: "low",
    placement_prob_6m: 0.61,
    salary_band_low_lpa: 35,
    salary_band_high_lpa: 48,
    loan_amount_requested: 2_100_000,
    status: "manual_review",
    submitted_at: new Date().toISOString(),
    document_completeness_pct: 71,
    roi_payback_years: 2.9,
    scholarship_dependency: "medium",
    candidate_quality: "strong",
    repayment_confidence_pct: 79,
  },
];
